Make `quipper_name` a class var in `Gate` with a default value of `undefined`. Fixes #138.
In `to_quipper`, no longer default to `name` if `quipper_name` is not defined.

Behaviour changes:
- calling `to_quipper` on `ParityPhase`, `InitAncilla`, and `PostSelect` will no longer cause a crash
  (`AttributeError: 'ParityPhase' object has no attribute 'target'. Did you mean: 'targets'?`)
- calling `to_quipper` on `FSim` and `DiscardBit` will result in a `TypeError: Gate {} doesn't have a Quipper description`
  (previous output was, e.g., 'QGate["FSim"](db) with nocontrol')